# @name health check
GET {{baseURL}}/api/health

####
# @name create userver
POST {{baseURL}}/api/userver
Content-Type: application/json

{
  "name": "ubuntu-local",
  "ip": "192.168.3.98",
  "port": "22",
  "timeout": "300"
}

####
# @name get uservers
GET {{baseURL}}/api/userver?limit=50&skip=0


####
# @name delete userver by id
DELETE {{baseURL}}/api/userver/6580f91f-37ee-4402-8f8e-706e78afd5bc

